### PR TITLE
fix :bug: after Wasserportal API change (closes #18)

### LINKED ISSUE #18: GW quality: API changed between 2021-11-08 and 2021-11-09 ?
At 2021-11-09 only GW data of last year is returned from Wasserportal Berlin:
https://raw.githubusercontent.com/KWB-R/wasserportal/387ca4549f8e8267974f9dd0a08a5a54ee1eafb4/stations_gwq_data.json

Until 2021-11-08 all available data points were returned:
https://raw.githubusercontent.com/KWB-R/wasserportal/6937763c6db0fa9ceb5f949a1f24af5554734089/stations_gwq_data.json

Source code for downloading was not changed in this time period: 
https://github.com/KWB-R/wasserportal/blob/master/vignettes/tutorial.Rmd#L287

@hsonne any idea if this can be fixed?

### PR DESCRIPTION
**Pull request by mrustl**
by explicitly provide a dummy start date ("01.01.1990") instead of "". For the latter only last years data were returned

---
This change is [Reviewable](https://reviewable.io/reviews/kwb-r/wasserportal/19)

### CODE REVIEW

File: R/read_wasserportal_raw_gw.R [hunk 1]
```diff
@@ -53,7 +52,7 @@ read_wasserportal_raw_gw <- function(
   # Format the start date
   #
   if (from_date != "") sdatum <- format(from_date, format = "%d.%m.%Y")
-  if (sreihe == "wa") sdatum <- ""
+  if (sreihe == "wa") sdatum <- format(as.Date("1900-01-01"), format = "%d.%m.%Y")
```
Comment (hsonne) [inline R/read_wasserportal_raw_gw.R:55]: This should result in "01.01.1990". Why not putting this directly?

Comment (mrustl) [reply R/read_wasserportal_raw_gw.R:55]: yeah you are right....but "01.01.1900" ;-)
